const DEFAULT={city:"Lubbock",region:"Texas",lat:33.5779,lon:-101.8552};
const STATE={unit:"F",place:{...DEFAULT},weatherC:null};

function cToF(c){return(c*9/5)+32;}function formatTemp(v){if(v==null||Number.isNaN(v))return"--";return Math.round(STATE.unit==="F"?cToF(v):v);}
function faviconFor(url){try{const u=new URL(url);return `https://www.google.com/s2/favicons?domain=${u.hostname}&sz=32`;}catch{return"";}}
function esc(s){return s?.replace(/[&<>"']/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))||'';}

async function resolveLocation(){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res(p),rej,{timeout:8000}));STATE.place.lat=pos.coords.latitude;STATE.place.lon=pos.coords.longitude;const rg=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${STATE.place.lat}&longitude=${STATE.place.lon}&localityLanguage=en`).then(r=>r.json());STATE.place.city=rg.city||rg.locality||DEFAULT.city;STATE.place.region=rg.principalSubdivision||rg.countryName||DEFAULT.region;}catch{STATE.place={...DEFAULT};}}

async function loadWeather(){const{lat,lon}=STATE.place;const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current_weather=true&daily=temperature_2m_max,temperature_2m_min&timezone=auto&forecast_days=1&temperature_unit=celsius`;const data=await fetch(url).then(r=>r.json());STATE.weatherC={current:data?.current_weather?.temperature,high:data?.daily?.temperature_2m_max?.[0],low:data?.daily?.temperature_2m_min?.[0]};document.getElementById('weatherLocation').textContent=`${STATE.place.city}, ${STATE.place.region}`;document.getElementById('currentTemp').textContent=formatTemp(STATE.weatherC.current);document.getElementById('highTemp').textContent=formatTemp(STATE.weatherC.high);document.getElementById('lowTemp').textContent=formatTemp(STATE.weatherC.low);}

async function fetchRSS(url){const prox='/.netlify/functions/rss?url='+encodeURIComponent(url);const xml=await fetch(prox).then(r=>{if(!r.ok)throw new Error('proxy failed');return r.text();});const doc=new DOMParser().parseFromString(xml,'text/xml');if(doc.querySelector('parsererror'))throw new Error('bad xml');return[...doc.querySelectorAll('item')].map(it=>({title:it.querySelector('title')?.textContent?.trim()||'',link:it.querySelector('link')?.textContent?.trim()||'',pubDate:it.querySelector('pubDate')?.textContent?.trim()||''}));}

async function loadUSNews(){const feed='https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en';try{const items=await fetchRSS(feed);document.getElementById('localNewsList').innerHTML=items.slice(0,10).map(i=>{const fav=faviconFor(i.link);const host=(()=>{try{return new URL(i.link).hostname.replace('www.','')}catch{return''}})();const date=i.pubDate?new Date(i.pubDate):null;const when=date?date.toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';return `<li class="item"><img class="favicon" src="${fav}"/><a href="${i.link}" target="_blank" rel="noopener">${esc(i.title)}</a> <span class="dim">${host}${when?' • '+when:''}</span></li>`}).join('');}catch(e){document.getElementById('localNewsList').innerHTML='<li class="dim">Error loading feed.</li>';console.warn(e);}}

async function loadReddit(){try{const data=await fetch('https://www.reddit.com/r/popular.json?limit=20').then(r=>r.json());const posts=(data?.data?.children||[]).map(x=>x.data);document.getElementById('redditList').innerHTML=posts.slice(0,12).map(p=>`<li>• <a href="https://www.reddit.com${p.permalink}" target="_blank" rel="noopener">${esc(p.title)}</a> <span class="dim">▲${new Intl.NumberFormat().format(p.ups||p.score||0)}</span></li>`).join('');}catch{document.getElementById('redditList').innerHTML='<li class="dim">Error loading Reddit.</li>';}}

const AI_FEEDS=["https://ai.googleblog.com/feeds/posts/default?alt=rss","https://openai.com/blog/rss/","https://huggingface.co/blog/feed.xml","https://venturebeat.com/category/ai/feed/","https://www.theverge.com/artificial-intelligence/rss/index.xml","https://ai.facebook.com/blog/rss/"];
async function loadAINews(){try{const all=[];for(const f of AI_FEEDS){try{all.push(...await fetchRSS(f));}catch{}}const cutoff=Date.now()-30*24*60*60*1000;const recent=all.filter(i=>{const t=Date.parse(i.pubDate||'');return t&&t>=cutoff;});recent.sort((a,b)=>Date.parse(b.pubDate||0)-Date.parse(a.pubDate||0));const seen=new Set(),dedup=[];for(const i of recent){if(!seen.has(i.link)){seen.add(i.link);dedup.push(i);}}document.getElementById('aiList').innerHTML=dedup.slice(0,20).map(i=>{const fav=faviconFor(i.link);const host=(()=>{try{return new URL(i.link).hostname.replace('www.','')}catch{return''}})();const date=i.pubDate?new Date(i.pubDate):null;const when=date?date.toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';return `<li class="item"><img class="favicon" src="${fav}"/><a href="${i.link}" target="_blank" rel="noopener">${esc(i.title)}</a> <span class="dim">${host}${when?' • '+when:''}</span></li>`}).join('');}catch{document.getElementById('aiList').innerHTML='<li class="dim">Error loading feed.</li>';}}

document.getElementById('unitToggle').addEventListener('click',()=>{STATE.unit=STATE.unit==='F'?'C':'F';document.getElementById('unitToggle').textContent='°'+STATE.unit;document.getElementById('currentTemp').textContent=formatTemp(STATE.weatherC.current);document.getElementById('highTemp').textContent=formatTemp(STATE.weatherC.high);document.getElementById('lowTemp').textContent=formatTemp(STATE.weatherC.low);});

(async()=>{try{await resolveLocation();}catch{}await loadWeather();await Promise.all([loadUSNews(),loadReddit(),loadAINews()]);})();